name: Deployment

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu latest
        steps:
           - name: Setup Node.js environment
             uses: actions/setup-node@v3
             with:
                node-version: 21

           - name: Install dependencies
             run: npm install
             
           - name: Run deployment
             run: npm run build

           - name: Get SSH key and set permissions
             run: |
               mkdir -p ~/.ssh
               echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
               ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts
             
           - name: Deploy to server using SSH
             run: ssh -i ~/.ssh/id_rsa user@your-server-ip "cd /path/to/your/app && git pull origin main && npm install && npm run start"







