name: Test on push

on:
    push: 
        branches:
            - somsom
    pull_request: 
        branches:
            - main        

jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with: 
                node-version: 21

            - name: Install dependencies
              run: npm install
            
            - name: Run tests
              run: npm test
